### ISSUE TITLE
mingw link error on v6.14.6

### ISSUE THREAD

**Issue by cculianu** [facebook/rocksdb#7764]
### Expected behavior

Building using mingw doesn't produce link errors.

### Actual behavior

Building using mingw produces link errors:

```
rocksdb/bin/win64/librocksdb.a(env_win.cc.obj):(.text+0xa68): undefined reference to `rocksdb::port::WindowsThread::join()'
```

### Steps to reproduce the behavior

1. Use Windows
2. Install mingw and cmake
3. Use it to build.
4. Get link error.

This used to work on rocksdb v6.6.4.

I ended up troubleshooting it and this is the culprit in `CMakeLists.txt`:

https://github.com/facebook/rocksdb/blob/8ff6557e7f096ed45de296a5073374958fbfaa55/CMakeLists.txt#L872

This was added after the last time I tried this and it worked (6.6.4).  Removing that conditional and unconditionally compiling that file and linking it fixes the problem.  I believe the problem happens because in the windows sources, the header for that `.cc` file is unconditionally included in `env_win.cc`, here: https://github.com/facebook/rocksdb/blob/8ff6557e7f096ed45de296a5073374958fbfaa55/port/win/env_win.cc#L13

**Suggested fix:** I suggest reverting the `CMakeLists.txt` back to also unconditionally compile the file `win_thread.cc`.

**Comment by petrutlucian94** [comment]
We were having issues with mingw, which required pthreads in order to use ``std::thread``. I'm not sure if that changed in recent mingw versions.

When using pthreads, win_thread.cc doesn't actually compile. I think we'd need a way to figure out the desired threading model, maybe by having a variable or simply check if the compiler has the ``-posix(\.exe)?`` suffix.

```
FAILED: CMakeFiles/rocksdb.dir/port/win/win_thread.cc.obj
ccache /usr/bin/x86_64-w64-mingw32-g++-posix  -DHAVE_PCLMUL -DHAVE_SSE42 -DLZ4 -DNOMINMAX -DOS_WIN -DROCKSDB_NO_DYNAMIC_EXTENSION -DROCKSDB_PTHREAD_ADAPTIVE_MUTEX -DROCKSDB_SUPPORT_THREAD_LOCAL -DSNAPPY -DWIN32 -DWIN64 -DZLIB -D_MBCS -D_POSIX=1 -D_POSIX_=1 -D_POSIX_C_SOURCE=1 -D_POSIX_THREADS=1 -D_WIN32_WINNT=_WIN32_WINNT_VISTA -I/mnt/ramdisk/workspace/ceph/src/rocksdb -I/mnt/ramdisk/workspace/ceph/src/rocksdb/include -I/mnt/ramdisk/workspace/ceph/src/rocksdb/third-party/folly -isystem /mnt/ramdisk/workspace/ceph/src/rocksdb/third-party/gtest-1.8.1/fused-src -isystem /mnt/ramdisk/workspace/ceph/build.deps/mingw/snappy/include -isystem /mnt/ramdisk/workspace/ceph/build.deps/mingw/zlib/include -isystem /mnt/ramdisk/workspace/ceph/build.deps/mingw/lz4/lib -Wno-deprecated-copy -Wno-pessimizing-move -W -Wextra -Wall -Wsign-compare -Wshadow -Wno-unused-parameter -Wno-unused-variable -Woverloaded-virtual -Wnon-virtual-dtor -Wno-missing-field-initializers -Wno-strict-aliasing -Wno-format -fno-asynchronous-unwind-tables -fno-omit-frame-pointer -momit-leaf-frame-pointer -fno-builtin-memcmp -O3 -DNDEBUG -DROCKSDB_USE_RTTI   -std=gnu++11 -MD -MT CMakeFiles/rocksdb.dir/port/win/win_thread.cc.obj -MF CMakeFiles/rocksdb.dir/port/win/win_thread.cc.obj.d -o CMakeFiles/rocksdb.dir/port/win/win_thread.cc.obj -c /mnt/ramdisk/workspace/ceph/src/rocksdb/port/win/win_thread.cc
/mnt/ramdisk/workspace/ceph/src/rocksdb/port/win/win_thread.cc: In member function ‘void rocksdb::port::WindowsThread::Init(std::function<void()>&&)’:
/mnt/ramdisk/workspace/ceph/src/rocksdb/port/win/win_thread.cc:49:20: error: ‘_beginthreadex’ was not declared in this scope 
   49 |   data_->handle_ = _beginthreadex(NULL,
      |                    ^~~~~~~~~~~~~~
```

**Comment by jay-zhuang** [comment]
Thanks @petrutlucian94. Assigning the issue to you for investigation. Please feel free to re-assign.
