### ISSUE TITLE
Erros when Make All

### ISSUE THREAD

**Issue by ssabnis** [facebook/rocksdb#4685]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Compile success
### Actual behavior
```
Makefile:156: Warning: Compiling in debug mode. Don't use the resulting binary in production
  GEN      util/build_version.cc
  CCLD     db_bench
util/testutil.o: In function `WritableFileWriter':
/root/rocksdb/./util/file_reader_writer.h:218: undefined reference to `rocksdb::SyncPoint::GetInstance()'
/root/rocksdb/./util/file_reader_writer.h:219: undefined reference to `rocksdb::SyncPoint::Process(std::string const&, void*)'
util/testutil.o:(.rodata._ZTIN7rocksdb4test22ChanglingMergeOperatorE[_ZTIN7rocksdb4test22ChanglingMergeOperatorE]+0x10): undefined reference to `typeinfo for rocksdb::MergeOperator'
collect2: error: ld returned 1 exit status
make: *** [db_bench] Error 1
```
### Steps to reproduce the behavior

Checkout the latest `master` branch and compile using `CentOS 7.4`
