### PR TITLE
Fix statistics in RocksJava sample

### PR DESCRIPTION
**Pull request by sagar0**
I observed while doing a `make jtest` that the java sample was broken, due to the changes in #2551 . 

Test Plan:
Before the fix:
```
cd rocksdb/java
make sample
javac -Xlint:deprecation -Xlint:unchecked -cp target/classes -d samples/target/classes samples/src/main/java/RocksDBSample.java
samples/src/main/java/RocksDBSample.java:44: error: cannot find symbol
            .createStatistics()
            ^
  symbol:   method createStatistics()
  location: class Options
samples/src/main/java/RocksDBSample.java:54: error: cannot find symbol
      final Statistics stats = options.statisticsPtr();
                                      ^
  symbol:   method statisticsPtr()
  location: variable options of type Options
samples/src/main/java/RocksDBSample.java:207: warning: [deprecation] remove(byte[]) in RocksDB has been deprecated
        db.remove(testKey);
          ^
2 errors
1 warning
make[1]: *** [sample] Error 1
```

After the fix:
No errors on doing a `make jtest` or `make sample`

### CODE REVIEW

File: java/samples/src/main/java/RocksDBSample.java [hunk 1]
```diff
@@ -31,6 +31,7 @@ public static void main(final String[] args) {
          final Filter bloomFilter = new BloomFilter(10);
          final ReadOptions readOptions = new ReadOptions()
              .setFillCache(false);
+         final Statistics stats = new Statistics();
```
Comment (adamretter) [inline java/samples/src/main/java/RocksDBSample.java]: Looks good. However `Statistics` is a `RocksObject` and so should ideally be manually closed, along with `ReadOptions`. Probably best to put them in a `try-with-resources`

Comment (sagar0) [inline java/samples/src/main/java/RocksDBSample.java]: But both Statistics and ReadOptions are already in try-with-resources here.

Comment (adamretter) [inline java/samples/src/main/java/RocksDBSample.java]: Sorry you are of course correct. I did not see it initially in the GitHub diff view. Sorry.
