### PR TITLE
Fix Windows Build broken by a recent commit

### PR DESCRIPTION
**Pull request by siying**
Windows build was broken by f4fce4751e16e5789bc7db60b88996298b97e47c and the error is:

c:\projects\rocksdb\db\db_test.cc(2993): error C3493: 'kNumPutsBeforeWaitForFlush' cannot be implicitly captured because no default capture mode has been specified

### CODE REVIEW

**Comment by grooverdan** [comment]
Well the compile error is fixed: https://ci.appveyor.com/project/Facebook/rocksdb/build/1.0.3682#L842
The DynamicMemtableOptions test passes https://ci.appveyor.com/project/Facebook/rocksdb/build/1.0.3682#L1298

There's a seeming unrelated test failure just before this however.

Apologies for not checking the results of AppVeyor previously
