### PR TITLE
Add OpenBSD Support

### LINKED ISSUE #11220: OpenBSD 7.2 error while building
### Expected behavior
builded RocksDB library
### Actual behavior
```
port/stack_trace.cc:133:5: error: use of undeclared identifier 'PrintStackTraceLine'
    PrintStackTraceLine((symbols != nullptr) ? symbols[i] : nullptr, frames[i]);
    ^
port/stack_trace.cc:143:56: error: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Werror,-Wshorten-64-to-32]
  PrintStack(&frames[first_frames_to_skip], num_frames - first_frames_to_skip);
  ~~~~~~~~~~                                ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
port/stack_trace.cc:156:23: error: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Werror,-Wshorten-64-to-32]
  *num_frames = count - first_frames_to_skip;
              ~ ~~~~~~^~~~~~~~~~~~~~~~~~~~~~
3 errors generated.
gmake: *** [Makefile:2529: port/stack_trace.o] Error 1
```
### Steps to reproduce the behavior
Try to build on OpenBSD through `gmake`

### PR DESCRIPTION
**Pull request by yelsohonnr**
I made some changes to add OpenBSD support.

Second time doing something like this, so I apologize in advance if I'm doing something wrong (had some minor hiccups with how github worked).

Fixes #11220

### CODE REVIEW

**Comment by ksilo** [comment]
Hi, can't compile on `OpenBSD 7.2`

```
  CC       util/crc32c.o
util/crc32c.cc:373:10: error: use of undeclared identifier 'crc32c_ppc'
  return crc32c_ppc(crc, (const unsigned char*)buf, size);
         ^
util/crc32c.cc:401:7: error: use of undeclared identifier 'arch_ppc_probe'
  if (arch_ppc_probe()) {
      ^
util/crc32c.cc:421:7: error: use of undeclared identifier 'arch_ppc_probe'
  if (arch_ppc_probe()) {
      ^
3 errors generated.

```

File: port/stack_trace.cc [hunk 1]
```diff
@@ -51,28 +55,40 @@ namespace port {
...
+  int mib[4] = {CTL_KERN, KERN_PROC_ARGS, getpid(), KERN_PROC_ARGV};
   size_t namesz = sizeof(name);
+  char* bin[namesz];
 
-  auto ret = sysctl(mib, 4, name, &namesz, nullptr, 0);
+  auto ret = sysctl(mib, 4, bin, &namesz, nullptr, 0);
   if (-1 == ret) {
     return nullptr;
   } else {
+    snprintf(name, sizeof(name), "%s", realpath(bin[0], nullptr));
```
Comment (ajkr) [inline port/stack_trace.cc:81]: I think we should handle `realpath()` failures, which might happen in case of (1) working directory changed and bin[0] is a relative path, or (2) command was invoked without its full path and relied on PATH env var to find it. (1) is kind of tricky - unless I'm missing something, it seems we might determine the wrong path in case the relative path can also be found under the changed working directory.

Also if we continue using `realpath()`, we should handle successes differently by freeing the string it returns.

What do you think about just printing `bin[0]` directly? Do we need the exact executable path for anything?

**Review by ajkr — CHANGES_REQUESTED** [review]

File: port/stack_trace.cc (hunk 1 above)
Comment (yelsohonnr) [reply port/stack_trace.cc:81]: Actually, using bin[0] directly should just work in this case.

Comment (yelsohonnr) [reply port/stack_trace.cc:81]: I'll make the changes this weekend.

**Review by ajkr — APPROVED** [review]
LGTM, thanks!
