### PR TITLE
Add ROCKSDB_LIBRARY_API macro to a few C APIs, to fix windows build

### PR DESCRIPTION
**Pull request by sagar0**
Windows build in AppVeyor is broken, I believe due to https://github.com/facebook/rocksdb/pull/2254.
Error messages:
```
c_test.obj : error LNK2019: unresolved external symbol rocksdb_get_pinned referenced in function CheckPinGet [C:\projects\rocksdb\build\c_test.vcxproj]
c_test.obj : error LNK2019: unresolved external symbol rocksdb_get_pinned_cf referenced in function CheckPinGetCF [C:\projects\rocksdb\build\c_test.vcxproj]
c_test.obj : error LNK2019: unresolved external symbol rocksdb_pinnableslice_destroy referenced in function CheckPinGet [C:\projects\rocksdb\build\c_test.vcxproj]
c_test.obj : error LNK2019: unresolved external symbol rocksdb_pinnableslice_value referenced in function CheckPinGet [C:\projects\rocksdb\build\c_test.vcxproj]
C:\projects\rocksdb\build\Debug\c_test.exe : fatal error LNK1120: 4 unresolved externals [C:\projects\rocksdb\build\c_test.vcxproj]
```
See, for example: https://ci.appveyor.com/project/Facebook/rocksdb/build/1.0.4420

Test Plan:
I don't have a local windows machine to make sure that this fixes the build; So I'll just depend on appveyor to see if this passes. 
`make check` on linux passes.

### CODE REVIEW

**Comment by tamird** [comment]
Looks like appveyor has passed 🎉

**Comment by sagar0** [comment]
Yup. Also just merged this code ... it should land shortly once it completes the mandatory internal checks.
