### ISSUE TITLE
C++ compilation errors on Linux using g++

### ISSUE THREAD

**Issue by mmucklo** [facebook/rocksdb#12686]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

rocksdb compiles fine using Linux (Ubuntu 22.04.4 LTS) with cmake 3.29 and g++ 11.4.0

### Actual behavior

A number of compilation errors mostly related to casts are reported and prevent compilation.

### Steps to reproduce the behavior

clone on Ubuntu and try building with g++

[PR#12685 is an attempt at a fix](https://github.com/facebook/rocksdb/pull/12685)
