### ISSUE TITLE
Compiling error lambda capture 'tracked_files' on MacOS

### ISSUE THREAD

**Issue by kildo162** [facebook/rocksdb#3900]
MacOS 10.13.4
clang version 7.0.0
java version "1.8.0_171"
releases RocksDB 5.13.1

### Actual behavior
`javah -cp target/classes:target/test-classes -d ./include -jni org.rocksdb.RocksDBExceptionTest org.rocksdb.NativeComparatorWrapperTest.NativeStringComparatorWrapper org.rocksdb.WriteBatchTest org.rocksdb.WriteBatchTestInternalHelper
java/rocksjni/sst_file_manager.cc:141:18: error: lambda capture 'tracked_files' is not used [-Werror,-Wunused-lambda-capture]
          [env, &tracked_files](
                 ^
1 error generated.
java/rocksjni/transaction_db.cc:312:17: error: lambda capture 'txn_db' is not used [-Werror,-Wunused-lambda-capture]
          [env, txn_db, &lock_status_data](
                ^
java/rocksjni/transaction_db.cc:312:26: error: lambda capture 'lock_status_data' is not used [-Werror,-Wunused-lambda-capture]
          [env, txn_db, &lock_status_data](
                         ^
2 errors generated.
make: *** [rocksdbjava] Error 1`
### Steps to reproduce the behavior
make -j8 rocksdbjava

**Comment by sagar0** [comment]
Does this also affect linux builds with clang?

**Comment by adamretter** [comment]
@sagar0 I don't have a Linux machine with Clang. It seems to have only appeared on my Mac recently, perhaps because of a newer version of Clang, but I am not certain.

**Comment by sagar0** [comment]
Could also be related to -Wunused-parameter flag introduced in 3be9b364539d382ce282cad80b5c05c58fd2d8a7 .

**Comment by sagar0** [comment]
We manually verified various jni build configurations when landing -Wunused-parameter changes, on linux, with gcc. But I think we missed testing with clang.

**Comment by kildo162** [comment]
I tried again but could not compile

5.12.4: Log
Generating target/apidocs/overview-summary.html...
Generating target/apidocs/help-doc.html...
26 warnings
java/rocksjni/transaction_db.cc:308:13: error: lambda capture 'txn_db' is not
      used [-Werror,-Wunused-lambda-capture]
      [env, txn_db, &lock_status_data](const std::pair<const int32_t, co...
            ^
java/rocksjni/transaction_db.cc:308:22: error: lambda capture 'lock_status_data'
      is not used [-Werror,-Wunused-lambda-capture]
      [env, txn_db, &lock_status_data](const std::pair<const int32_t, co...
                     ^
2 errors generated.

And new code:

Generating target/apidocs/overview-summary.html...
Generating target/apidocs/help-doc.html...
22 warnings
java/rocksjni/sst_file_manager.cc:141:18: error: lambda capture 'tracked_files'
      is not used [-Werror,-Wunused-lambda-capture]
          [env, &tracked_files](
                 ^
1 error generated.

**Comment by adamretter** [comment]
@kildo you need the fix referenced in #3904
