### ISSUE TITLE
rocksdb fails to compile in Fedora 28 / gcc version 8.0.1

### ISSUE THREAD

**Issue by itamarjp** [facebook/rocksdb#3716]
[root@f28 rocksdb]# make
Makefile:129: Warning: Compiling in debug mode. Don't use the resulting binary in production
  GEN      util/build_version.cc
  CC       db/c.o
db/c.cc: In function 'void rocksdb_writebatch_wi_iterate(rocksdb_writebatch_wi_t*, void*, void (*)(void*, const char*, size_t, const char*, size_t), void (*)(void*, const char*, size_t))':
db/c.cc:1683:5: error: conflicting C language linkage declaration 'rocksdb_writebatch_wi_iterate(rocksdb_writebatch_wi_t*, void*, void (*)(void*, const char*, size_t, const char*, size_t), void (*)(void*, const char*, size_t))::H handler' [-Werror]
   H handler;
     ^~~~~~~
db/c.cc:1427:5: note: previous declaration 'rocksdb_writebatch_iterate(rocksdb_writebatch_t*, void*, void (*)(void*, const char*, size_t, const char*, size_t), void (*)(void*, const char*, size_t))::H handler'
   H handler;
     ^~~~~~~
db/c.cc: In function 'rocksdb_slicetransform_t* rocksdb_slicetransform_create_fixed_prefix(size_t)':
db/c.cc:3315:12: error: conflicting C language linkage declaration 'rocksdb_slicetransform_create_fixed_prefix(size_t)::Wrapper* wrapper' [-Werror]
   Wrapper* wrapper = new Wrapper;
            ^~~~~~~
db/c.cc:2869:12: note: previous declaration 'rocksdb_filterpolicy_create_bloom_format(int, bool)::Wrapper* wrapper'
   Wrapper* wrapper = new Wrapper;
            ^~~~~~~
db/c.cc: In function 'rocksdb_slicetransform_t* rocksdb_slicetransform_create_noop()':
db/c.cc:3336:12: error: conflicting C language linkage declaration 'rocksdb_slicetransform_create_noop()::Wrapper* wrapper' [-Werror]
   Wrapper* wrapper = new Wrapper;
            ^~~~~~~
db/c.cc:2869:12: note: previous declaration 'rocksdb_filterpolicy_create_bloom_format(int, bool)::Wrapper* wrapper'
   Wrapper* wrapper = new Wrapper;
            ^~~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:1868: db/c.o] Error 1
[root@f28 rocksdb]#

**Comment by itamarjp** [comment]
full build log with the failure, here ->

https://koji.fedoraproject.org/koji/taskinfo?taskID=26351599

**Comment by itamarjp** [comment]
I think probably should be a good idea do use github webhooks to launch automatic builds on copr / fedora, they allways use the lasted gcc-c++ please take a look -> copr.fedorainfracloud.org

**Comment by inikep** [comment]
I confirm the same issues with gcc-8 under Ubuntu 14.04 and 16.04. 

You can test gcc-8 with Travis by adding:
```
       sudo -E apt-add-repository -y "ppa:jonathonf/binutils";
       sudo -E apt-add-repository -y "ppa:jonathonf/gcc-8.0";
       sudo -E apt-get -yq --no-install-suggests --no-install-recommends install g++-8;
```

**Comment by yiwu-arbug** [comment]
@inikep thanks for sending the fix and I think it is a good idea to test with gcc8 on travis. I'll check with @gfosco to see if travis capacity is a concern.

**Comment by tamird** [comment]
This was fixed in #3736.

**Comment by itamarjp** [comment]
thank you.
