### PR TITLE
fix build for rocksdb lite

### PR DESCRIPTION
**Pull request by miasantreble**
currently rocksdb lite build fails due to the following errors:
> db/db_sst_test.cc:29:51: error: ‘FlushJobInfo’ does not name a type
   virtual void OnFlushCompleted(DB* /*db*/, const FlushJobInfo& info) override {
                                                   ^
db/db_sst_test.cc:29:16: error: ‘virtual void rocksdb::FlushedFileCollector::OnFlushCompleted(rocksdb::DB*, const int&)’ marked ‘override’, but does not override
   virtual void OnFlushCompleted(DB* /*db*/, const FlushJobInfo& info) override {
                ^
db/db_sst_test.cc:24:7: error: ‘class rocksdb::FlushedFileCollector’ has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
 class FlushedFileCollector : public EventListener {
       ^
db/db_sst_test.cc: In member function ‘virtual void rocksdb::FlushedFileCollector::OnFlushCompleted(rocksdb::DB*, const int&)’:
db/db_sst_test.cc:31:35: error: request for member ‘file_path’ in ‘info’, which is of non-class type ‘const int’
     flushed_files_.push_back(info.file_path);
                                   ^
cc1plus: all warnings being treated as errors
make: *** [db/db_sst_test.o] Error 1

### CODE REVIEW

File: db/db_sst_test.cc [hunk 1]
```diff
@@ -14,6 +14,7 @@
 #include "util/sst_file_manager_impl.h"
 
 namespace rocksdb {
+#ifndef ROCKSDB_LITE
```
Comment (sagar0) [inline db/db_sst_test.cc]: I think `ifndef ROCKSDB_LITE` should be added only around FlushedFileCollector and DBSSTTest .CancellingManualCompactionsWorks test. (introduced in #3670).

Comment (miasantreble) [reply db/db_sst_test.cc]: well currently the `ifndef ROCKSDB_LITE` is covering line 125 to line 1026.
My change basically excludes two more tests `DontDeletePendingOutputs` and `SSTsWithLdbSuffixHandling` for rocksdb lite. 
As long as these two tests are not must-have for rocksdb lite, I think we are all good here?
