### ISSUE TITLE
Compilation fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by Kixunil** [facebook/rocksdb#7307]
According to https://github.com/romanz/electrs/issues/292 rocksdb fails to compile on Ubuntu 20.04.

Cc @burguesia

### Expected behavior
The library compiles

### Actual behavior
```
rocksdb/util/channel.h:35:33: error: no matching constructor for initialization of 'std::lock_guard<std::mutex>'
```

### Steps to reproduce the behavior
Run `"c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.7.0/fused-src/" "-I" "snappy/" "-I" "lz4/lib/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "zlib/" "-I" "bzip2/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DLZ4=1" "-DZSTD=1" "-DZLIB=1" "-DBZIP2=1" "-DNDEBUG=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/home/witnet/electrs/target/release/build/librocksdb-sys-66bfcafa6869bfa8/out/rocksdb/utilities/backupable/backupable_db.o" "-c" "rocksdb/utilities/backupable/backupable_db.cc"` on Ubuntu 20.04

**Comment by cheng-chang** [comment]
https://github.com/facebook/rocksdb/pull/7330
