### ISSUE TITLE
fix build with gflags 2.1.x

### ISSUE THREAD

**Issue by ajkr** [facebook/rocksdb#6628]
With either make or cmake, building against gflags 2.1.x leads to errors like:

```
In file included from /home/andrewkr/local/rocksdb/tools/trace_analyzer_tool.cc:49:0:
/home/andrewkr/local/rocksdb/util/gflags_compat.h:11:26: error: ‘google’ has not been declared
 #define GFLAGS_NAMESPACE google
```

In gflags 2.1, the namespace changed from google to gflags. Meanwhile, it wasn't until 2.2 that the macro `#define GFLAGS_NAMESPACE ...` was introduced to a header file. So for 2.1 versions, this logic improperly guesses the namespace: https://github.com/facebook/rocksdb/blob/57096ab13e9d373666f099f19d6eb73c6613e797/util/gflags_compat.h#L8-L12.

**Comment by iFA88** [comment]
Hey @ajkr , sorry but i have still issue with this workaround `-D GFLAGS_NAMESPACE=gflags` :
```
CMake Warning:
  Manually-specified variables were not used by the project:

    GFLAGS_NAMESPACE
```
After build i can not use the library:
`/usr/lib/x86_64-linux-gnu/librocksdb.so.6: undefined symbol: _ZN6google21ParseCommandLineFlagsEPiPPPcb`

libgflags-dev has v2.1.2-4 on debian 9.

Rocksdb v6.8.1 works fine.

**Comment by ajkr** [comment]
For the workaround, `-DGFLAGS_NAMESPACE` should be provided as a compiler flag, not as a CMake build option.
