### ISSUE TITLE
Failed to compile from cmake

### ISSUE THREAD

**Issue by jay-zhuang** [facebook/rocksdb#7075]
### Expected behavior
```
$ mkdir cmake-build && cd cmake-build && cmake .. && make
```
Successfully build.

### Actual behavior
Failed to compile `testharness`, it happens after https://github.com/facebook/rocksdb/commit/741b9ba96bb103f57380768508fa961f03427cb7, reverting the change fixes problem.
Error:
```
In file included from /Users/zjay/ws/rocksdb/test_util/testharness.cc:10:
/Users/zjay/ws/rocksdb/test_util/testharness.h:38:67: error: unknown type name 'Status'; did you mean 'rocksdb::Status'?
::testing::AssertionResult AssertStatus(const char* s_expr, const Status& s);
                                                                  ^~~~~~
                                                                  rocksdb::Status
/usr/local/include/rocksdb/status.h:25:7: note: 'rocksdb::Status' declared here
class Status {
      ^
/Users/zjay/ws/rocksdb/test_util/testharness.cc:17:67: error: unknown type name 'Status'; did you mean 'rocksdb::Status'?
::testing::AssertionResult AssertStatus(const char* s_expr, const Status& s) {
                                                                  ^~~~~~
                                                                  rocksdb::Status
/usr/local/include/rocksdb/status.h:25:7: note: 'rocksdb::Status' declared here
class Status {
      ^
/Users/zjay/ws/rocksdb/test_util/testharness.cc:26:20: error: unknown type name 'Env'
std::string TmpDir(Env* env) {
                   ^
/Users/zjay/ws/rocksdb/test_util/testharness.cc:28:3: error: unknown type name 'Status'; did you mean 'rocksdb::Status'?
  Status s = env->GetTestDirectory(&dir);
  ^~~~~~
  rocksdb::Status
/usr/local/include/rocksdb/status.h:25:7: note: 'rocksdb::Status' declared here
class Status {
      ^
/Users/zjay/ws/rocksdb/test_util/testharness.cc:42:29: error: unknown type name 'Env'
std::string PerThreadDBPath(Env* env, std::string name) {
                            ^
5 errors generated.
make[2]: *** [CMakeFiles/testharness.dir/test_util/testharness.cc.o] Error 1
make[1]: *** [CMakeFiles/testharness.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

### Steps to reproduce the behavior
```
$ mkdir cmake-build && cd cmake-build && cmake .. && make
```

**Comment by ajkr** [comment]
hm looks like it's including some RocksDB headers through your system path: "/usr/local/include/rocksdb/status.h"

And some of the names in the compiled file look like "::testing::AssertionResult". My guess is your locally installed RocksDB predates the `ROCKSDB_NAMESPACE` macro leading it to expand to empty (normally the previously mentioned name would look like "rocksdb::testing::AssertionResult").

How it relates to  741b9ba I'm not sure.. Maybe `GFLAGS_INCLUDE_DIR` is "/usr/local/include/"?

**Comment by jay-zhuang** [comment]
Thanks @ajkr . Yes, you're right, I have an older version of rocksdb installed on my host, which has header files in `/usr/local/include/rocksdb/...`.
The build passes after I uninstall the local rocksdb:
```
$ brew uninstall rocksdb
```
