### PR TITLE
Fix build with libcxx 20.1.8

### PR DESCRIPTION
**Pull request by 4JustMe4**
This include is required for `free` since libcxx about version 20.1.8.
```
/root/rocksdb/util/stderr_logger.cc:17:5: error: use of undeclared identifier 'free'
   17 |     free((void*)log_prefix);
      |     ^
1 error generated.
```

### CODE REVIEW

**Comment by 4JustMe4** [comment]
Signed CLA
