### PR TITLE
Mark virtual ~Env() override

### PR DESCRIPTION
**Pull request by hx235**
**Context:**

Compiling RocksDB with -Winconsistent-missing-destructor-override reveals the following :

```
./include/rocksdb/env.h:174:11: error: '~Env' overrides a destructor but is not marked 'override' [-Werror,-Winconsistent-missing-destructor-override]
  virtual ~Env();
          ^
./include/rocksdb/customizable.h:58:3: note: overridden virtual function is here
  ~Customizable() override {}
```

The need of overriding the Env's destructor seems to be introduced by https://github.com/facebook/rocksdb/pull/9293 and surfaced by -Winconsistent-missing-destructor-override, which is not turned on by default.

**Summary:**
Mark  ~Env() override

**Test:**
- Turn on -Winconsistent-missing-destructor-override and USE_CLANG=1 make -jN env/env.o to see whether the error shows up

### CODE REVIEW

File: include/rocksdb/env.h [hunk 1]
```diff
@@ -171,7 +171,7 @@ class Env : public Customizable {
   Env(const Env&) = delete;
   void operator=(const Env&) = delete;
 
-  virtual ~Env();
+  virtual ~Env() override;
```
Comment (riversand963) [inline include/rocksdb/env.h:174]: According to `-modernize-use-override`(https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-override.html), we should remove `virtual` and keep `override`.

**Review by riversand963 — APPROVED** [review]
Minor, and it's up to you:
should we do a sweeping update for all destructors and/or methods in public headers?
Otherwise, LGTM.

File: include/rocksdb/env.h (hunk 1 above)
Comment (hx235) [reply include/rocksdb/env.h]: TIL :)

**Comment by hx235** [comment]
A follow up could be https://github.com/facebook/rocksdb/pull/9404#issuecomment-1017007721
