### ISSUE TITLE
RocksDB fails to compile with g++ 7.1

### ISSUE THREAD

**Issue by benesch** [facebook/rocksdb#2382]
```
$ g++-7 --version
g++-7 (Homebrew GCC 7.1.0) 7.1.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ CC=gcc-7 CXX=g++-7 make 
Makefile:105: Warning: Compiling in debug mode. Don't use the resulting binary in production
  GEN      util/build_version.cc
  CC       db/builder.o
In file included from ./db/write_batch_internal.h:14:0,
                 from ./db/column_family.h:22,
                 from ./db/version_set.h:33,
                 from ./db/compaction.h:13,
                 from ./db/compaction_iterator.h:16,
                 from db/builder.cc:18:
./db/write_thread.h: In member function 'std::mutex& rocksdb::WriteThread::Writer::StateMutex()':
./db/write_thread.h:227:78: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
       return *static_cast<std::mutex*>(static_cast<void*>(&state_mutex_bytes));
                                                                              ^
cc1plus: all warnings being treated as errors
make: *** [db/builder.o] Error 1
```

This seems to be [reported downstream in Ceph](http://tracker.ceph.com/issues/19864) as well.

**Comment by benesch** [comment]
Actually, this seems to be a bug in GCC itself that's fixed in trunk: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80593

Leaving this open in case there's an easy fix. It's not clear to me why `write_thread.h` uses `std::aligned_storage` at all.

**Comment by yiwu-arbug** [comment]
@joscollin reported it earlier: #2302. I guess working around a compiler bug is not a good idea, since it will make our code base messy. Closing for now.

**Comment by grooverdan** [comment]
FYI I have tested with x86_64-pc-linux-gnu-g++ (GCC) 8.0.0 20170605 (experimental) from their master and there is no warning for the jl/db/builder.o(db/builder.cc) build.
