### PR TITLE
Fix strncpy not copying the whole string

### PR DESCRIPTION
**Pull request by cfabio**
Not sure if this is the best way to solve the issue but at least this way it compiles without throwing errors.

### CODE REVIEW

**Comment by maysamyabandeh** [comment]
I do not see any problem with the existing code. The best approach is start with reporting an issue with a unit test that reproducea the problem.

**Comment by cfabio** [comment]
RocksDB fails to compile on Fedora 28 (GCC version 8.0.1) with the following error:
`/rocksdb/util/status.cc:28:15: error: ‘char* strncpy(char*, const char*, size_t)’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
   std::strncpy(result, state, cch - 1);
   ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~`
This pull request was supposed to fix the issue.

**Comment by maysamyabandeh** [comment]
Is `-Wstringop-truncation` is a default rocksdb setting?

**Comment by cfabio** [comment]
I suppose so, what I did was following what is written here: `https://github.com/facebook/rocksdb/blob/master/INSTALL.md`.
Installed the required dependencies, git clone the repo and run `make static_lib`.

**Comment by maysamyabandeh** [comment]
I do not find it being set by rockdb. We need to figure how this setting made it to your built.
