### ISSUE TITLE
No longer builds with NIOSTATS_CONTEXT

### ISSUE THREAD

**Issue by ronag** [facebook/rocksdb#10475]
```
../deps/rocksdb/rocksdb/logging/env_logger.h:60:7: error: use of undeclared identifier 'iostats_context'; did you mean 'get_iostats_context'?
      iostats_context.disable_iostats = true;
      ^~~~~~~~~~~~~~~
      get_iostats_context
../deps/rocksdb/rocksdb/include/rocksdb/iostats_context.h:95:17: note: 'get_iostats_context' declared here
IOStatsContext* get_iostats_context();
                ^
In file included from ../deps/rocksdb/rocksdb/env/env.cc:18:
../deps/rocksdb/rocksdb/logging/env_logger.h:60:22: error: member reference base type 'rocksdb::IOStatsContext *()' is not a structure or union
      iostats_context.disable_iostats = true;
      ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
../deps/rocksdb/rocksdb/logging/env_logger.h:65:7: error: use of undeclared identifier 'iostats_context'; did you mean 'get_iostats_context'?
      iostats_context.disable_iostats = false;
      ^~~~~~~~~~~~~~~
      get_iostats_context
../deps/rocksdb/rocksdb/include/rocksdb/iostats_context.h:95:17: note: 'get_iostats_context' declared here
IOStatsContext* get_iostats_context();
                ^
In file included from ../deps/rocksdb/rocksdb/env/env.cc:18:
../deps/rocksdb/rocksdb/logging/env_logger.h:65:22: error: member reference base type 'rocksdb::IOStatsContext *()' is not a structure or union
      iostats_context.disable_iostats = false;
```

**Comment by ronag** [comment]
Seems to be caused by cc2099803a1de4dab8aa748cb26b2650e740d197

**Comment by ronag** [comment]
@siying

**Comment by siying** [comment]
Thanks for pointing it out, will fix.
